<a href="https://colab.research.google.com/github/drashoksharma/machine-learning/blob/main/Copy_of_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LOGISTIC REGRESSION** üê± üëå

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
df = pd.read_csv('/content/dataregression.csv', header=0)

In [ ]:
#to display top 5 
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#drop null values
df = df.dropna()

In [ ]:
#display all feilds
print(list(df.columns))

['UID', 'Gender', 'Age', 'Estimated Salary', 'Computer Purchase ']

**SPLITING DATA**

In [ ]:
data = pd.get_dummies(df,columns= ['UID',	'Gender',	'Age',	'Estimated Salary', 'Computer Purchase '])

X = data.iloc[:,1:]

In [ ]:
data.head()

,UID_1,UID_2,UID_3,UID_4,UID_5,UID_6,UID_7,UID_8,UID_9,UID_10,...,Estimated Salary_67000,Estimated Salary_70000,Estimated Salary_80000,Estimated Salary_89000,Estimated Salary_100000,Estimated Salary_145000,Estimated Salary_210000,Estimated Salary_230000,Computer Purchase _0,Computer Purchase _1
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
data.columns

Index(['UID_1', 'UID_2', 'UID_3', 'UID_4', 'UID_5', 'UID_6', 'UID_7', 'UID_8',
       'UID_9', 'UID_10',
       ...
       'Estimated Salary_67000', 'Estimated Salary_70000',
       'Estimated Salary_80000', 'Estimated Salary_89000',
       'Estimated Salary_100000', 'Estimated Salary_145000',
       'Estimated Salary_210000', 'Estimated Salary_230000',
       'Computer Purchase _0', 'Computer Purchase _1'],
      dtype='object', length=112)

In [ ]:

data

,UID_1,UID_2,UID_3,UID_4,UID_5,UID_6,UID_7,UID_8,UID_9,UID_10,...,Estimated Salary_67000,Estimated Salary_70000,Estimated Salary_80000,Estimated Salary_89000,Estimated Salary_100000,Estimated Salary_145000,Estimated Salary_210000,Estimated Salary_230000,Computer Purchase _0,Computer Purchase _1
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
36,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
43,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
44,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
46,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
49,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
51,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
52,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
53,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
54,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
55,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
56,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
57,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
58,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
#to create an array for predicted value column
Y = data.iloc[:,0]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=0)

**Building classifier**

In [ ]:
classifier = LogisticRegression(solver='lbfgs',random_state=0)

In [ ]:
classifier.fit(X_train, Y_train)

LogisticRegression(random_state=0)

**TESTING**

In [ ]:
predicted_y = classifier.predict(X_test)

In [ ]:
predicted_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
for x in range(len(predicted_y)):
   if (predicted_y[x] == 1):
      print(x, end="\t")

**ACCURACY**

In [ ]:
print('Accuracy: {:.2f}'.format(classifier.score(X_test, Y_test)))

Accuracy: 1.00

In [ ]:

classifier.coef_

array([[-0.02145796,  0.        , -0.03241813,  0.        , -0.01771163,
        -0.0107563 , -0.00969039, -0.01645931, -0.02006009,  0.        ,
         0.        , -0.03259665, -0.01934516, -0.03367387, -0.01923367,
        -0.01649169, -0.01799726, -0.00946523, -0.01066413, -0.03182676,
        -0.03241813,  0.        , -0.01828056, -0.01098051, -0.01003133,
         0.        , -0.03267088,  0.        , -0.02015282,  0.        ,
        -0.01019177, -0.01784127,  0.        ,  0.        ,  0.        ,
        -0.01706951, -0.03382368, -0.01056246, -0.03541006,  0.        ,
         0.        , -0.0098629 ,  0.        , -0.010103  , -0.01625789,
         0.        , -0.02039836, -0.03254984, -0.0098236 , -0.01670146,
        -0.0103907 , -0.03184841, -0.0188477 , -0.01724995, -0.01109411,
        -0.01667992, -0.01625789, -0.01741569, -0.27311218,  0.27311065,
         0.82476111, -0.02145796, -0.02173681, -0.06190584, -0.13267106,
        -0.01109411, -0.01771163, -0.01066413, -0.0979763 , -0.03382368,
        -0.01056246, -0.09894104,  0.        , -0.08739662, -0.03627782,
        -0.12673474, -0.03541006, -0.02039836, -0.0098629 ,  0.82476111,
        -0.03221426, -0.03241813, -0.01667992, -0.01098051,  0.        ,
        -0.01784127, -0.01109411, -0.06961619,  0.        , -0.05195612,
         0.        , -0.08607046, -0.02728128, -0.03241813, -0.01741569,
        -0.06195999, -0.0365194 , -0.03259665, -0.03448895, -0.06270941,
        -0.03541006, -0.02746021, -0.0199266 , -0.01828056, -0.04921725,
        -0.02015282,  0.        , -0.01019177,  0.        ,  0.35602894,
        -0.35603046]])

In [ ]:
classifier.reshape(-1, 1)

AttributeError: ignored

In [ ]:

cm = confusion_matrix(predicted_y, classifier.predict(x))

fig, ax = plt.subplots(figsize=(8, 8))
ax.imshow(cm)
ax.grid(False)
ax.xaxis.set(ticks=(0, 1), ticklabels=('Predicted 0s', 'Predicted 1s'))
ax.yaxis.set(ticks=(0, 1), ticklabels=('Actual 0s', 'Actual 1s'))
ax.set_ylim(1.5, -0.5)
for i in range(2):
    for j in range(2):
        ax.text(j, i, cm[i, j], ha='center', va='center', color='black')
plt.show()

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

ValueError: ignored